name: publish

on:
  push:
    tags: ['*']

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run build
          zip -r koishi-plugin-qtail.zip dist package.json
      - if: github.ref_type == 'tag'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: koishi-plugin-qtail.zip