name: Publish to npm

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: build and publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
